# Common
common:
  database:
    path: /home/highxsky/highxsky/pokemon_airflow/include/poke_api/db/poke_db.db
    connection_id: poke_db
    timeout: 30
  api:
    base_url: "https://pokeapi.co/api/v2/"
    rate_limit_requests: 100
  retry:
    max_attempts: 3
    delay_minutes: 1
  poke_gen:
    generation: 1

# DAG specific
dags:
  ingest_gen_pokemons:
    schedule: "@once"

  ingest_random_pokemons:
    schedule: "@daily"
    num_random: 3