transforms:
  target: dev

  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', 'poke_db.duckdb') }}"
      schema: dbt_dev
      threads: 4
    prod:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH', 'poke_db.duckdb') }}"
      schema: analytics
      threads: 4
