version: 2
sources:
  - name: raw
    schema: raw
    tables:
      - name: pokemon_data
        description: Pokemon's detailed data fetched from the PokeAPI in raw state
        loaded_at_field: fetch_date
        freshness:
          warn_after: {count: 15, period: day}
          error_after: {count: 30, period: day}
        columns:
          - name: id
            description: A pokemon's identifier
            data_type: INTEGER
          - name: fetch_date
            description: Datetime when a pokemon was fetched
            data_type: TIMESTAMP
          - name: batch_id
            description: Airflow DAG batch ID
            data_type: VARCHAR
          - name: payload
            description: JSON payload fetched from PokeAPI
            data_type: JSON
      - name: pokemon_catalogue
        description: Pokemon's catalogue data fetched from the PokeAPI in raw state
        loaded_at_field: fetch_date
        freshness:
          warn_after: {count: 180, period: day}
          error_after: {count: 360, period: day}
        columns:
          - name: fetch_date
            description: Datetime when a pokemon was fetched
            data_type: TIMESTAMP
          - name: batch_id
            description: Airflow DAG batch ID
            data_type: VARCHAR
          - name: payload
            description: JSON payload fetched from PokeAPI
            data_type: JSON
      - name: version_group_data
        description: Version group data fetched from the PokeAPI in raw state
        loaded_at_field: fetch_date
        freshness:
          warn_after: {count: 360, period: day}
          error_after: {count: 720, period: day}
        columns:
          - name: fetch_date
            description: Datetime when the version group was fetched
            data_type: TIMESTAMP
          - name: batch_id
            description: Airflow DAG batch ID
            data_type: VARCHAR
          - name: payload
            description: JSON payload fetched from PokeAPI
            data_type: JSON
      - name: generation_data
        description: Generation data fetched from the PokeAPI in raw state
        loaded_at_field: fetch_date
        freshness:
          warn_after: {count: 360, period: day}
          error_after: {count: 720, period: day}
        columns:
          - name: fetch_date
            description: Datetime when the generation was fetched
            data_type: TIMESTAMP
          - name: batch_id
            description: Airflow DAG batch ID
            data_type: VARCHAR
          - name: payload
            description: JSON payload fetched from PokeAPI
            data_type: JSON