version: 2
sources:
  - name: raw
    schema: raw
    tables:
      - name: pokemon_data
        description: Pokemon's detailed data fetched from the PokeAPI in raw state
        loaded_at_field: fetch_date
        freshness:
          warn_after: {count: 15, period: day}
          error_after: {count: 30, period: day}
        columns:
          - name: id
            description: A pokemon's identifier
            data_type: INTEGER
          - name: fetch_date
            description: Datetime when a pokemon was fetched
            data_type: TIMESTAMP
          - name: batch_id
            description: Airflow DAG batch ID
            data_type: VARCHAR
          - name: generation
            description: Generation of a pokemon
            data_type: SMALLINT
          - name: raw
            description: JSON array fetched from PokeAPI
            data_type: JSON
      - name: pokemon_catalogue
        description: Pokemon's catalogue data fetched from the PokeAPI in raw state
        loaded_at_field: fetch_date
        freshness:
          warn_after: {count: 6, period: month}
          error_after: {count: 12, period: month}
        columns:
          - name: fetch_date
            description: Datetime when a pokemon was fetched
            data_type: TIMESTAMP
          - name: raw
            description: JSON array fetched from PokeAPI
            data_type: JSON